[build]
  publish = "."

[[headers]]
  for = "/data/fabs.json"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate"
    Pragma = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
